### ISSUE TITLE
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'newTag')

### ISSUE THREAD

**Issue by ItsMisa** [pedroslopez/whatsapp-web.js#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An error occurred while executing the code `client.initialize()`  Evaluation failed: TypeError: Cannot read properties of undefined (reading 'newTag')

### Expected behavior

`client.initialize()` can be executed normally

### Steps to Reproduce the Bug or Issue

1. Do  client.initialize()
2. see error : Evaluation failed: TypeError: Cannot read properties of undefined (reading 'newTag')

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Mac
Phone OS: iOS
whatsapp-web.js version [e.g. 1.2.3]
WhatsApp Web version [run await client.getWWebVersion()]: 1.15.7
Node.js Version : v14.16.0

**Comment by AGG-an** [comment]
+1

**Comment by zhiying8710** [comment]
and `window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach queryExists MD'))[0].default;`

Cannot read properties of undefined (reading 'default')

**Comment by AGG-an** [comment]
Temporary solutions to newTag errors
`    const gid = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('self.crypto.getRandomValues'))[0];
    window.Store.genId = gid ? gid.default : ()=>Promise.reject();
    window.Store.genId() // {key: "XXXXXXXXXXXXXXX", timestamp: 1646709164}
    `
    Note that the returned value becomes object

**Comment by StiflerPasha** [comment]
Maybe use `window.Store.MsgKey.newId()` ?

**Comment by NowDev** [comment]
+1

**Comment by StiflerPasha** [comment]
`window.ReactStore.genId = window.mR.findModule('newTag')[0]?.newTag || window.ReactStore.MsgKey?.newId`

**Comment by cassfer** [comment]
> 

I made the above changes and had to change the part of line 30 where it was 'Should not reach queryExists MD' I changed it to 'Should not reach'.

**window.Store.QueryExist = window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;**

**Comment by cassfer** [comment]
> Temporary solutions i found:
> 
> Comment the line 17 **window.Store.genId = window.mR.findModule('newTag')[0].newTag;** And the line 30 **window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach queryExists MD'))[0].default;**
> 
> Inside the function: **exports.LoadUtils = () => {**
> 
> add the next line: **window.Store.genId = window.Store.MsgKey.newId;**

I made the above changes and had to change the part of line 30 where it was 'Should not reach queryExists MD' I changed it to 'Should not reach'.

**window.Store.QueryExist = window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;**

**Comment by alexandrereyes** [comment]
To fix: Drop your whatsapp md directory and authenticate again.....
There is no BUG, looks like is some dirty in MD directory....

**Comment by jaovitubr** [comment]
```js
window.Store.genId = window.mR.findModule('genId')?.[0]?.genId || window.mR.findModule('newTag')[0].newTag;
window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach here'))[0].default
```

**Comment by ItsMisa** [comment]
> Line 14
> 
> ```
> window.Store.genId = window.mR.findModule('newTag')?.[0]?.newTag || null;
> ```
> 
> Line 30
> 
> ```
> window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;
> ```
> 
> Line 74 (First line inside `exports.LoadUtils`)
> 
> ```js
> if(!window.Store.genId) {
>     window.Store.genId = window.Store.MsgKey.newId;
> }
> ```
> 
> That's works for me 👀
> 
> **NOTE:**
> 
> > this error doesn't happen all the time, if you delete the session folder and scan again it doesn't happen...
> > but after a few hours it comes back.
> > That's why I have it as validation.


thanks your reply, I changed the code according to the code you provided, the error didn't happen, but the interface `isRegisteredUser` didn't work, I use the `isRegisteredUser` interface to check the phonenumber which has been registered in whatsapp, it returns false

**Comment by zhiying8710** [comment]
@ItsMisa i use old version code `window.Store.Wap.queryExist` to do the same thing as you

**Comment by moshe212** [comment]
I do not understand what to do.. it is still happen to me..
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'newTag')

how can i fix this?
i do not understand the fix's you suggest up..
someone can explain to me where i need to change the code..

**Comment by navneetnis1** [comment]
> Temporary solutions i found:
> 
> Comment the line 17 **window.Store.genId = window.mR.findModule('newTag')[0].newTag;** And the line 30 **window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach queryExists MD'))[0].default;**
> 
> Inside the function: **exports.LoadUtils = () => {**
> 
> add the next line: **window.Store.genId = window.Store.MsgKey.newId;**

In which page we have to add/delete this code?

**Comment by xXDeathAbyssXx** [comment]
> 

All temp solutions for this problem go here: `src/util/Injected.js` ✅

**Comment by KevinEduardo** [comment]
I'm also having this issue, only with WhatsApp Business. Using everything latest, all the packages, the app version, and the web version.

**Comment by mackawara** [comment]
Having the same issue but it is failing on client.initialise .Seems its a puppeteer issue

**Comment by eowoosh** [comment]
Having the same issue

**Comment by AbrahamHuertaDev** [comment]
Check this commit it is clear where the changes are [1311](https://github.com/pedroslopez/whatsapp-web.js/pull/1311)

**Comment by AbrahamHuertaDev** [comment]
Check this [1311](https://github.com/pedroslopez/whatsapp-web.js/pull/1311) here are the changes, they released [1.16.4-alpha.0](https://www.npmjs.com/package/whatsapp-web.js/v/1.16.4-alpha.0) version

**Comment by sidikhanrei** [comment]
Try #1313 https://github.com/pedroslopez/whatsapp-web.js/issues/1313#issuecomment-1063086393

**Comment by adityakumar48** [comment]
> > Line 14
> > ```
> > window.Store.genId = window.mR.findModule('newTag')?.[0]?.newTag || null;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Line 30
> > ```
> > window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Line 74 (First line inside `exports.LoadUtils`)
> > ```js
> > if(!window.Store.genId) {
> >     window.Store.genId = window.Store.MsgKey.newId;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's works for me 👀
> > **NOTE:**
> > > this error doesn't happen all the time, if you delete the session folder and scan again it doesn't happen...
> > > but after a few hours it comes back.
> > > That's why I have it as validation.
> 
> thanks your reply, I changed the code according to the code you provided, the error didn't happen, but the interface `isRegisteredUser` didn't work, I use the `isRegisteredUser` interface to check the phonenumber which has been registered in whatsapp, it returns false

I tried but not worked for me

**Comment by GustavoSilva84** [comment]
> Soluções temporárias para erros de newTag ` const gid = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('self.crypto.getRandomValues'))[0]; window.Store.genId = gid ? gid.default : ()=>Promise.reject(); window.Store.genId() // {key: "XXXXXXXXXXXXXXX", timestamp: 1646709164}` Observe que o valor retornado se torna objeto

where should i put this code?

**Comment by xXDeathAbyssXx** [comment]
> I tried but not worked for me

If no work, the line 14 is not about `newTag`, so re-install the package again and do this

---

Replace the line 17 to this:

```js
window.Store.genId = window.mR.findModule('newTag')?.[0]?.newTag || null;
```
----

Replace the line 30 to this:

```js
window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;
```

---

Add below line 73 (`exports.LoadUtils = () => {`) this:


```js
if(!window.Store.genId) {
    window.Store.genId = window.Store.MsgKey.newId;
}
```

Your lines from 73 to 77 should look like this:

```js
exports.LoadUtils = () => {
    if(!window.Store.genId) {
        window.Store.genId = window.Store.MsgKey.newId;
    }
    window.WWebJS = {};
```

----

All of this temp solutions for this problem go here: `src/util/Injected.js` ✅

**Comment by josuelmm** [comment]
Same error but
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'cast')

**Comment by DogLife2007** [comment]
GUYS! If you need a fast fix: delete whatsapp-web.js directory from node_modules and clone the git repo in the node_modules directory.

**Comment by kirasillent** [comment]
> Line 14
> ```
> window.Store.genId = window.mR.findModule('newTag')?.[0]?.newTag || null;
> ```
> 
> Line 30
> ```
> window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;
> ```
> 
> Line 74 (First line inside `exports.LoadUtils`)
> ```js
> if(!window.Store.genId) {
>     window.Store.genId = window.Store.MsgKey.newId;
> }
> ```
> 
> That's works for me 👀 
> 
> **NOTE:**
> 
> > this error doesn't happen all the time, if you delete the session folder and scan again it doesn't happen... 
> > but after a few hours it comes back.
> > 
> > That's why I have it as validation.

This also works for me 😄

**Comment by mackawara** [comment]
Halo guys. They have released this version https://www.npmjs.com/package/whatsapp-web.js/v/1.16.4-alpha.0 which clears this bug

**Comment by pedroslopez** [comment]
The temporary fix released as an alpha is now released as 1.16.4. The reason this was a weird one is because whatsapp was serving up two different versions, and the fix wasn't compatible with the older version. It seems whatsapp web is now always serving 2.2208.7, so it should be ok now.

**Comment by adityakumar48** [comment]
> > I tried but not worked for me
> 
> If no work, the line 14 is not about `newTag`, so re-install the package again and do this
> 
> Replace the line 17 to this:
> 
> ```js
> window.Store.genId = window.mR.findModule('newTag')?.[0]?.newTag || null;
> ```
> 
> Replace the line 30 to this:
> 
> ```js
> window.Store.QueryExist = window.mR.findModule(module => typeof module.default === 'function' && module.default.toString().includes('Should not reach'))[0].default;
> ```
> 
> Add below line 73 (`exports.LoadUtils = () => {`) this:
> 
> ```js
> if(!window.Store.genId) {
>     window.Store.genId = window.Store.MsgKey.newId;
> }
> ```
> 
> Your lines from 73 to 77 should look like this:
> 
> ```js
> exports.LoadUtils = () => {
>     if(!window.Store.genId) {
>         window.Store.genId = window.Store.MsgKey.newId;
>     }
>     window.WWebJS = {};
> ```
> 
> All of this temp solutions for this problem go here: `src/util/Injected.js` ✅

replaced line no. 17 this worked me thanks buddy

**Comment by loginweb-dev** [comment]
update app, for 1.16.4 alpha
all, ok

**Comment by garikaib** [comment]
> r 1.16.4

Indeed this is what worked for me. npm i whatsapp-web.js@1.16.4-alpha.0 I will admit I was too lazy to go digging into the code. I come from the WordPress core world where touching the core/someone else's library code is considered a no no.

**Comment by priti0802** [comment]
I am not able to solve this line query can u help for the same.

 Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'QueryExist')


0|indexServer  |     at __puppeteer_evaluation_script__:2:47
0|indexServer  |     at ExecutionContext._evaluateInternal (/root/SendingSystem/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|indexServer  |     at runMicrotasks (<anonymous>)
0|indexServer  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|indexServer  |     at async ExecutionContext.evaluate (/root/SendingSystem/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
0|indexServer  |     at async Client.getNumberId (/root/SendingSystem/node_modules/whatsapp-web.js/src/Client.js:949:16)
0|indexServer  |     at async Client.isRegisteredUser (/root/SendingSystem/node_modules/whatsapp-web.js/src/Client.js:935:24)
