### ISSUE TITLE
How to send video file?

### ISSUE THREAD

**Issue by yudhatira21** [pedroslopez/whatsapp-web.js#134]
How to send video file?

**Comment by enggaraziz** [comment]
you should convert to base64 data.

**Comment by meirinaldojunior** [comment]
You need instance google chrome, see it: #78

**Comment by m7mdcc** [comment]
I tried that not working , here is sample code : 

```
async function ReadVideo(filename){
  return await promisify(fs.readFile)(filename,'base64');

}
  videodata= await utils.ReadVideo("./tmp/videoname.mp4")
  var VideoMessage = new MessageMedia('video/mp4',videodata)

  client.sendMessage(msg.from, VideoMessage)
```


Its working good with images , chrome used .

**Comment by pedroslopez** [comment]
@m7mdcc what does your videodata contain?

**Comment by m7mdcc** [comment]
> @m7mdcc what does your videodata contain?
Youtube video file , is that what you mean ?

**Comment by pedroslopez** [comment]
> @pedroslopez  Youtube video file , is that what you mean ? 
> 
> 

@m7mdcc I mean, what exactly does your ReadVideo function return?

**Comment by m7mdcc** [comment]
Its return base64 of the the video file . i have try to store the value in file to be sure .

**Comment by ninnoh** [comment]
same error here
