### ISSUE TITLE
Database error shows every time on my end

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Database error shows every time when I start new session. and node js app stops detecting QR Code.
![error in whatsapp](https://user-images.githubusercontent.com/32213812/163354792-12e78e22-b4cb-4632-a579-d5826c33c29d.JPG)

### Expected behavior

Application should detect QR Code or refresh the page automatically.

### Steps to Reproduce the Bug or Issue

1- started the session
2- after generating 2 QR Code this error happens

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Ubuntu

**Comment by stefanfuchs** [comment]
You browser might be having trouble saving data to the local storage.
Maybe the disk is full or the browser is corrupted?

Maybe try another browser or another machine to be sure?

**Comment by stefanfuchs** [comment]
Puppeteer might also not be able to save data to the disk. Check if the puppeteer user data dir has write permissions.

**Comment by tasaddaq-rana** [comment]
I have to manuly refresh the page, then it works fine, but untill then node app doesn't capture QR code

**Comment by rafalfs** [comment]
I'm having the same issue. When i scan the qr code for the first time it works but when i try to restore a previous session using the clientId that I logged in previously it doesn't restore the session and instead show me the qr code. But when I Scan the code on this scenario I have the exact same error message.
If I delete the .wwebjs_auth folder and force the wpp logout session from wpp app and do again the steps above It always gives me this error.

Resuming the steps that I do to get the error:
1 - delete .wwebjs_auth folder
2 - delete any active session from whatsapp app
3 - login using a clientId (QR scan successfully)
4 - stops the application
5 - starts the application again
6 - try to reconnect the client using the clientId
7 - reconnection fails and it ask me again for QRCode
8 - scanning QR code gives the error message "database error occurred on your browser. Please restart your computer and relink your device" on browser

**Comment by mikelustosa** [comment]
I have the same problem. Did anyone get a solution?

**Comment by vitlib** [comment]
Same problem, using Ferdi on Ubuntu

**Comment by luiscuriel** [comment]
I get the same problems but randomly... sometimes (very frequent) chromium crashes and the session is lost...
