### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/32213812/164459467-76369fbd-96e9-42d1-b12b-a24aeab928dd.png)

From last night I am getting this issue

### Expected behavior

Doesn't expect any error

### Steps to Reproduce the Bug or Issue

when try to send message then this error comes

### Relevant Code

client.sendMessage(number, message, {}).then((r) => {
res.send({phone: phone, sendState: '202'});
}).catch(err => {
console.log("err:", err)
res.send({msg: err, sendState: '502'});
});

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: [e.g. Mac, Windows, Linux, Docker + Ubuntu 18, etc]
Phone OS: [e.g. Android, iOS]

**Comment by PurpShell** [comment]
> Are you adding "@.us" in phone end? ex: [123123@c.us](mailto:123123@c.us)

`@c.us` **

**Comment by tasaddaq-rana** [comment]
> Are you adding "@c.us" in phone end? ex: [123123@c.us](mailto:123123@c.us)

yes, I am using numbers ending with @c.us

**Comment by matibjolivera** [comment]
Try updating to https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.16.6

**Comment by ShineiIchijo** [comment]
I tried updating but it didn't work for me
