### ISSUE TITLE
Error: Evaluation failed: Error: wid error: invalid wid: xxxxxxxx@c.us

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error: Evaluation failed: Error: wid error: invalid wid: xxxxxxxx@c.us
    at new l (https://web.whatsapp.com/bootstrap_qr.7585ad81c65e2056813e.js:69:27564)
    at Object.s [as createWid] (https://web.whatsapp.com/bootstrap_qr.7585ad81c65e2056813e.js:69:31906)
    at __puppeteer_evaluation_script__:2:53

### Expected behavior

 Message should be sent

### Steps to Reproduce the Bug or Issue

1. When try to send message
2. Error

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Linux

**Comment by jessepaniza** [comment]
I'm having the same issue :(

**Comment by josegb** [comment]
I'm having a similar issue.
 
Error: Evaluation failed: Error: wid error: invalid wid: false@c.us
  at new l (https://web.whatsapp.com/bootstrap_qr.b472ccf746046d1080f9.js:69:27564)
  at Object.s [as createWid] (https://web.whatsapp.com/bootstrap_qr.b472ccf746046d1080f9.js:69:31906)
  at __puppeteer_evaluation_script__:2:53

**Comment by EpicJosch** [comment]
I have the same issue

**Comment by jeanvcastro** [comment]
I have the same issue

**Comment by rhutikcodes** [comment]
Same issue :)

**Comment by jorgegonvar** [comment]
TENGO ESTE CODIGO Y AL MOMENTO QUE INTENTO CORRER EL HOLA QUE DEBERIA DEVOLVER UN BOTON ME SALE EL ERROR QUE ESTA EN LA IMAGEN, ALGUIEN SABE POR QUÉ? 

TENGO WHATS APP NORMAL, DESDE UN TELEFONO ANDROID, USO MULTI DISPOSITIVO

const client2 = new Client({
    authStrategy: new LocalAuth({ clientId: "client-two" })
});

client2.on('ready', () => {
    console.log('Client 2 is ready!');
});

client2.initialize();

client2.on('message', message => {
console.log(message.body);
});

var nombre

button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');

client2.on('message', message =>
 {

msj=message.body
id=message.id

	if(msj === 'Buenos dias') 
	{
		client2.sendMessage(message.from, "nombre");
			msj.reply(nombre)
	} else{
		if (msj === "Hola")
		 {
		 button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
        client2.sendMessage(msj.from, button);
		}
	} 

});
![image](https://user-images.githubusercontent.com/108782355/177473762-9c978d45-cdad-47d3-9e5b-f730cc7e61c1.png)

**Comment by PurpShell** [comment]
> TENGO ESTE CODIGO Y AL MOMENTO QUE INTENTO CORRER EL HOLA QUE DEBERIA DEVOLVER UN BOTON ME SALE EL ERROR QUE ESTA EN LA IMAGEN, ALGUIEN SABE POR QUÉ?
> 
> TENGO WHATS APP NORMAL, DESDE UN TELEFONO ANDROID, USO MULTI DISPOSITIVO
> 
> const client2 = new Client({ authStrategy: new LocalAuth({ clientId: "client-two" }) });
> 
> client2.on('ready', () => { console.log('Client 2 is ready!'); });
> 
> client2.initialize();
> 
> client2.on('message', message => { console.log(message.body); });
> 
> var nombre
> 
> button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
> 
> client2.on('message', message => {
> 
> msj=message.body id=message.id
> 
> ```
> if(msj === 'Buenos dias') 
> {
> 	client2.sendMessage(message.from, "nombre");
> 		msj.reply(nombre)
> } else{
> 	if (msj === "Hola")
> 	 {
> 	 button = new Buttons('Button body',[{body:'bt1'},{body:'bt2'},{body:'bt3'}],'title','footer');
>     client2.sendMessage(msj.from, button);
> 	}
> } 
> ```
> 
> }); ![image](https://user-images.githubusercontent.com/108782355/177473762-9c978d45-cdad-47d3-9e5b-f730cc7e61c1.png)

message.from
