### ISSUE TITLE
Nothing happened when adding participants

### ISSUE THREAD

**Issue by ycrz** [pedroslopez/whatsapp-web.js#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

nothing happened when trying to add number (not in contact) to specific group

### Expected behavior

i expected the number can add to the group

### Steps to Reproduce the Bug or Issue

client.getChats().then((chats) => {
    const myGroupName = 'example';
    const myGroup = chats.find((chat) => chat.name === myGroupName);
    myGroup.addParticipants(['number@c.us']);
})

### Relevant Code

client.getChats().then((chats) => {
    const myGroupName = 'example';
    const myGroup = chats.find((chat) => chat.name === myGroupName);
    myGroup.addParticipants(['number@c.us']);
})

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

whatsapp-web.js version 1.17.0

**Comment by PurpShell** [comment]
closed by mistake!

**Comment by ycrz** [comment]
Wow! thanks @PurpShell for the response! yep the barrier was group privacy setting.
