### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by pedroslopez** [pedroslopez/whatsapp-web.js#155]
Hi everyone!

I've now created a Discord server for this library that can be used for general help and discussion. Please note that bug reports and feature requests should always be reported through a GitHub Issue so that progress can be tracked.

You can join the server here: https://discord.gg/H7DqQs4.

Looking forward to chat with you there!

**Comment by PurpShell** [comment]
I will be including the Discord in my "before opening a issue" pinned issue, and the discord is mentioned in the new issue menu

so I will be unpinning this issue
