### ISSUE TITLE
[BUG] QueryExists throws the error 'user must have an id or a phone' on a verified business number

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when try to check number is register or not.

### Expected behavior

Number should be verified

### Steps to Reproduce the Bug or Issue

check number is registered or not

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Getting error Uncaught Error: user must have an id or a phone

**Comment by bvr218** [comment]
please helpp!!!

**Comment by nuz-faiz** [comment]
there is the same problem  please  help!!! 
@pedroslopez

**Comment by yaroslov-moore** [comment]
Instead of using `QueryExist` use the `queryPhoneExists` module.

```javascript
// inject into "window" object.
window.Store.QueryPhoneExists = window.mR.findModule('queryPhoneExists')[0].queryPhoneExists;

const phoneNumber = "+31 6 3...";
const doesExist = await window.Store.QueryPhoneExists(phoneNumber);
```

**Comment by PurpShell** [comment]
> Instead of using `QueryExist` use the `queryPhoneExists` module.
> 
> ```js
> // inject into "window" object.
> window.Store.QueryPhoneExists = window.mR.findModule('queryPhoneExists')[0].queryPhoneExists;
> 
> const phoneNumber = "+316...";
> const doesExist = await window.Store.QueryPhoneExists(phoneNumber);
> ```

Can you write a PR? or at least test the efficacy of both `QueryExist` and `queryPhoneExists`?
