### ISSUE TITLE
Evalution failed: Error: wid error: invalid wid

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![pp](https://user-images.githubusercontent.com/32213812/215397824-ef22abab-2c81-4408-ba34-818e20f4e09b.JPG)

I am having this error Evalution failed: Error: wid error: invalid wid

### Expected behavior

should send message

### Steps to Reproduce the Bug or Issue

start whatsapp
send whatsapp
error

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Windows

**Comment by iamohsin** [comment]
do not add + sign with phone number

**Comment by iamohsin** [comment]
it is appropriate to add the "+" symbol when providing a phone number remove + sign from phone number

**Comment by boomfly** [comment]
Phone format: 77071234567@c.us
