### ISSUE TITLE
Validation whether the message is really sent or not

### ISSUE THREAD

**Issue by ycrz** [pedroslopez/whatsapp-web.js#2031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

my app has procedure to send the message.
1. Get the data from db when grabstatus 0
2. Send the message
3. Flag grabstatus to 1
(repeat)

Therefore, not every message can be send due to the number is not a whatsapp number, error on library etc. So if it error, i can flag the grabstatus column to 2, for us to evaluate the error message.

### Describe the solution you'd like.

It is nice to have if whatsapp-js has validation after i run client.sendMessage command and decide whether the status is 1 (success) or 2 (not success). Thank you!

**Comment by alechkos** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> my app has procedure to send the message.
> 
> 1. Get the data from db when grabstatus 0
> 2. Send the message
> 3. Flag grabstatus to 1
>    (repeat)
> 
> Therefore, not every message can be send due to the number is not a whatsapp number, error on library etc. So if it error, i can flag the grabstatus column to 2, for us to evaluate the error message.
> 
> ### Describe the solution you'd like.
> It is nice to have if whatsapp-js has validation after i run client.sendMessage command and decide whether the status is 1 (success) or 2 (not success). Thank you!
> 
> ### Describe an alternate solution.
> _No response_
> 
> ### Additional context
> _No response_

the functional is already implemented here
https://github.com/pedroslopez/whatsapp-web.js/blob/6f2ad1773e6bb34b1f916f6485114bc1b26c837b/src/Client.js#L396

usage example:

```js
client.on('onMessageAckEvent', (message, ack) => {
    console.log(message);
    console.log(ack);
});
```
