### ISSUE TITLE
Chats from number@lid

### ISSUE THREAD

**Issue by cmadridDev** [pedroslopez/whatsapp-web.js#2330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

What do the messages that I receive from recipients with number@lid mean?
Until now, I had only handled @c.us and @g.us.

That number does not exist in whatsapp if I add it as a number.
How can I get it?

### Expected behavior

understand the operation of the numbers with @lid, I did not find in the documentation or references in the code

### Steps to Reproduce the Bug or Issue

Receive messages from those numbers

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Ubuntu 22
Phone OS:  Android
whatsapp-web.js version: 1.21.0
Node.js Version [18]

**Comment by imaperson1060** [comment]
I think the `lid` server is from whenever a community admin enables the number privacy feature to hide all non-admin numbers from participants.

**Comment by RATHIM253** [comment]
> I think the `lid` server is from whenever a community admin enables the number privacy feature to hide all non-admin numbers from participants.
> 
> If you use `Client.getChatById("...@lid")` with the number, it will trick WhatsApp into returning the name of the chat with that person, which will be either a formatted phone number or a contact name.

Hi can you explain in detail. I am not able to get number from LID

**Comment by imaperson1060** [comment]
It's possible that WhatsApp blocked that in a later update. All I did was `await client.getChatById("...@lid")``` and it returned the chat with the contact. This doesn't give you all their information (the phone number property is hidden), but as mentioned earlier, you can get their `pushname`. In this case, it will either be their contact name if you have them saved in contacts, or it will be their phone number.

The way I'd test it is by doing ```console.log(await client.getChatById("...@lid"));``` and then using the JSON output to find the correct properties.

**Comment by alechkos** [comment]
`XXXXXXXXXX@lid` is a hidden user ID, each user has a regular ID along with a hidden one.
WhatsApp added that type of an ID along with communities functionality.

**Comment by RDKclick** [comment]
> getChatById("xxx@lid")

 Does this method still work? I used it to directly return my own information to me

**Comment by N0N4M3BNS** [comment]
> > getChatById("xxx@lid")
> 
> Does this method still work? I used it to directly return my own information to me

@RDKclick not work to me, your side working?

**Comment by AKhateeb** [comment]
I had a function to store the phone numbers of the group participants, and now I'm getting all participants as `xxxx@lid`.
I tried "GetClassInfo"; it's not including the phone number in the response. (I'm using the account of the group admin)

Could anyone please tell me how to find the phone number? If it's something blocked by WhatsApp, then how can we still see the phone numbers of participants using the WhatsApp mobile application

**Comment by N0N4M3BNS** [comment]
> I had a function to store the phone numbers of the group participants, and now I'm getting all participants as `xxxx@lid`. I tried "GetClassInfo"; it's not including the phone number in the response. (I'm using the account of the group admin)
> 
> Could anyone please tell me how to find the phone number? If it's something blocked by WhatsApp, then how can we still see the phone numbers of participants using the WhatsApp mobile application

@AKhateeb Im report already in this https://github.com/pedroslopez/whatsapp-web.js/issues/3519 but no body talk about that

**Comment by WateenSolution** [comment]
Anyone find the solution please share it with me as well. Thanks in advance.

Error: Lid origin type is missing in chat table at new Error (:6:31) at i (https://static.whatsapp.net/rsrc.php/v4/yf/r/1llVN9bYZPM.js:76:180) at Object.callback (https://static.whatsapp.net/rsrc.php/v4iTtf4/ys/l/rt/xGU63EBhzn5.js:676:231) at Object. (https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:7685) at https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:67100 at Array.map () at https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:66948 at https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:17483 at jb (https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:14343) at ob (https://static.whatsapp.net/rsrc.php/v4/yj/r/68hTCFFAw1C.js:237:15012)

**Comment by Dhruv108-ui** [comment]
Can I get a lid from a phone number?

**Comment by vinithedev** [comment]
I found a way:
```
const chatId = msg.id.participant ? msg.author : msg.from
const authorPhone = (await client.getChatById(chatId)).id.user
console.log(`authorPhone = ${authorPhone}`)
```

**Comment by leoneDuarte** [comment]
Hello, name. In case none of that works, the author is coming as null. I had to do it this way, and it worked for me                        
`
let chat = await sessions[number].getChatById(msg.from);

msg.from = chat.name?.replace(/\D/g, '') + '@c.us';
`

**Comment by mohshaqilshaqil-cyber** [comment]
62476051 95808154300547@lid( 62344093 15823380996170@lid(
