### ISSUE TITLE
Library with update error

### ISSUE THREAD

**Issue by maliqto** [pedroslopez/whatsapp-web.js#3118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Report

**Describe the bug**
Whenever I'm trying to create some code using the `whatsapp-web.js` library, with updated Node.js or in old versions like 18.0, it displays the error:

Additionally, some deprecated warnings appear when I run `npm install whatsapp-web.js`.

**To Reproduce**
1. Create a new Node.js project or use an existing one.
2. Install `whatsapp-web.js` by running:
   ```bash
   npm install whatsapp-web.js```
3. Output Console:
```npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated puppeteer@18.2.1: < 22.6.4 is no longer supported
```

### Expected behavior

I expected it to execute the command perfectly, and run the script without errors. I've already tested it on old versions and codes from the site's own API

### Steps to Reproduce the Bug or Issue

Claro! Aqui está o campo "Steps to Reproduce" formatado para você colocar na issue:

---

**Steps to Reproduce the Bug or Issue**

1. Create a new Node.js project or use an existing one.
2. Run the following command to install `whatsapp-web.js`:
   ```
   npm install whatsapp-web.js
   ```
3. Observe the deprecation warnings during the installation process:
   - `npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.`
   - `npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported`
   - `npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported`
   - `npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported`
   - `npm WARN deprecated fstream@1.0.12: This package is no longer supported.`
   - `npm WARN deprecated puppeteer@18.2.1: < 22.6.4 is no longer supported`

4. Attempt to create and run code using the `whatsapp-web.js` library.
5. Notice the following error when using the library with Node.js (tested with both updated versions and 18.0):
   ```javascript
   const version = indexHtml.match(/manifest-([\d\\.]+)\.json/ )[1];
   ```

---

Copie e cole esses passos na seção "Steps to Reproduce the Bug or Issue" ao criar a sua issue no GitHub. Isso ajudará os mantenedores a entenderem os passos exatos que você seguiu para reproduzir o problema.

### Browser Type

Other (please write in Additional Context)

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

- **OS**: Windows
- **Phone OS**: IOS AND ANDROID
- **whatsapp-web.js version**: 1.23.0
- **WhatsApp Web version**  22.13.74
- **Node.js Version**: 19.9.0

### Additional context

my browser is brave

**Comment by alechkos** [comment]
#1621
