### ISSUE TITLE
problem npm i whatsapp-web.js

### ISSUE THREAD

**Issue by taylanguneyaktas** [pedroslopez/whatsapp-web.js#458]
root@c11afed33348:/# npm i whatsapp-web.js
npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

+ whatsapp-web.js@1.11.1
updated 1 package and audited 225 packages in 1.63s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@c11afed33348:/# npm fund
/
+-- https://github.com/sponsors/ljharb
| `-- resolve@1.19.0, is-core-module@2.2.0
+-- https://github.com/sponsors/feross
| `-- safe-buffer@5.2.1, buffer@5.7.1, base64-js@1.5.1, ieee754@1.2.1
+-- https://www.patreon.com/feross
| `-- safe-buffer@5.2.1, buffer@5.7.1, base64-js@1.5.1, ieee754@1.2.1
+-- https://feross.org/support
| `-- safe-buffer@5.2.1, buffer@5.7.1, base64-js@1.5.1, ieee754@1.2.1
+-- https://github.com/sponsors/isaacs
| `-- rimraf@3.0.2, glob@7.1.6
`-- https://github.com/sponsors/sindresorhus
  `-- get-stream@5.2.0, p-limit@2.3.0

root@c11afed33348:/#

**Comment by pedroslopez** [comment]
Seems like you haven't initialized your project folder. Just run `npm init` and it should create the package.json for you.

**Comment by taylanguneyaktas** [comment]
delete all my issues
