### ISSUE TITLE
Maryam

### ISSUE THREAD

**Issue by alirezaebiii** [pedroslopez/whatsapp-web.js#623]
09101404305
`###` Bug description

### Reproduction steps
1. 
2.
3.
...

### Relevant code
If applicable, add code snippets to help explain your problem.

### Environment (please complete the following information):
**WhatsApp**
 - Account type [Standard / Business]:
 - Device OS [iOS / Android]:
 - WhatsApp Web version [run `await client.getWWebVersion()`]:

**Library**
 - Browser [Chrome / Chromium]:
 - NodeJS version (`node -v`):
 - npm or yarn version (`npm -v`):
 - whatsapp-web.js version:

**Comment by alirezaebiii** [comment]
1. ### 9101404305*/message

`**ali**
//WhatsApp

- get chat WhatsApp to Us9332828148 

1.

**Comment by alirezaebiii** [comment]
- [ ] 
Maryam
- [ ] seesioniD and free time

**Comment by PurpShell** [comment]
what
