### ISSUE TITLE
1. ### 9101404305*/message

### ISSUE THREAD

**Issue by alirezaebiii** [pedroslopez/whatsapp-web.js#628]
1. ### 9101404305*/message

`**ali**
//WhatsApp

- get chat WhatsApp to Us9332828148 

1.

_Originally posted by @alirezaebiii in https://github.com/pedroslopez/whatsapp-web.js/issues/623#issuecomment-814439827_

**Comment by PurpShell** [comment]
close this

**Comment by alirezaebiii** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/628#issuecomment-814630911
