### ISSUE TITLE
Send media with sendMessage by media URL

### ISSUE THREAD

**Issue by sostenesapollo** [pedroslopez/whatsapp-web.js#705]

**Comment by fdciabdul** [comment]
file url ? did u mean with access some url ?

**Comment by PurpShell** [comment]
This would require a downloader.. You can do this locally: 
```js 
new MessageMedia("MIME", (await axios.get(url, {response:"arraybuffer"})).toString("base64"), null)
```

**Comment by PurpShell** [comment]
Closing this issue, you are welcome to open it again if you think this was done in error. 

Useful Links:
- [**Starter Guide**](https://waguide.pedroslopez.me)
- [**Documentation**](https://pedroslopez.me/whastapp-web.js)
- Questions? Chat with us on [**Discord**](https://discord.gg/wyKybbF)

Best regards, 

[PurpShell](https://github.com/PurpShell)

**Comment by PurpShell** [comment]
@pedroslopez thoughts?

**Comment by sostenesapollo** [comment]
Thanks purp. But that can be added a new function, like in Baileys and venom

**Comment by pedroslopez** [comment]
> @pedroslopez thoughts?

We could add something like we did for `MessageMedia.fromFilePath` that takes care of this for you.

**Comment by sostenesapollo** [comment]
cool
