### ISSUE TITLE
typeerror: cannot read property 'evaluate' of null

### ISSUE THREAD

**Issue by nandacahyangtiapratama** [pedroslopez/whatsapp-web.js#708]
### Bug description
I have an error "typeerror: cannot read property 'evaluate' of null" after my code execute all method
Example: client.sendMessage, client.getContacts()

Can you help me?

**Comment by PurpShell** [comment]
this means this.pupPage is null. You haven't started your client?

**Comment by nandacahyangtiapratama** [comment]
i have a file base ("./base/configWhatsappAPI.js")
`const { Client } = require("whatsapp-web.js");
const whatsappAPI = {
  client: Client,
};

module.exports = whatsappAPI;`

and code in app.js
`var createError = require("http-errors");
var express = require("express");
var path = require("path");
var cookieParser = require("cookie-parser");
var logger = require("morgan");
var socketIO = require("./base/configSocket");
var Client = require("./base/configWhatsappAPI");
var qrcode = require("qrcode-terminal");
var fs = require("fs");

var indexRouter = require("./routes/index");
var usersRouter = require("./routes/users");
var sendRouter = require("./routes/send");
var getContactRouter = require("./routes/contact");

var app = express();

// view engine setup
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));

app.use("/", indexRouter);
app.use("/users", usersRouter);
app.use("/v1", sendRouter);
app.use("/v1", getContactRouter);

// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render("error");
});

const SESSION_FILE_PATH = "./session.json";
let sessionCfg;
if (fs.existsSync(SESSION_FILE_PATH)) {
  sessionCfg = require(SESSION_FILE_PATH);
}

const client = new Client.client({
  puppeteer: { headless: true },
  session: sessionCfg,
});

client.initialize();

client.on("qr", (qr) => {
  console.log(`QR Code: ${qr}`);
  qrcode.generate(qr, { small: true });
});

client.on("authenticated", (session) => {
  console.log("AUTHENTICATED", session);
  sessionCfg = session;
  fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
    if (err) {
      console.error(err);
    }
  });
});

client.on("auth_failure", (msg) => {
  // Fired if session restore was unsuccessfull
  console.error("AUTHENTICATION FAILURE", msg);
});

client.on("ready", () => {
  // console.log(client);
  // const data = client.getContacts();
  // console.log(data);
  getID();
  console.log("Client is ready !!!");
  client.getState().then((result) => {
    if (!result.match("CONNECTED")) {
      throw Error("Whatsapp not Connected");
    } else {
      console.log(`Whatsapp State ${result}`);
    }
  });
});

async function getID() {
  const data = await client.getContactById("6281232702611@c.us");
  console.log(data);
}

client.getContacts().then((contact) => {
  contact.forEach((contact) => {
    if (contact.id.server == "c.us" && contact.isMyContact == true) {
      console.log(`${contact.name} - ${contact.number}`);
    }
  });
});

client.on("message", async (msg) => {
  console.log("MESSAGE RECEIVED", msg);

  if (msg.body === "!ping") {
    msg.reply("pong");
  } else if (msg.body === "!mention") {
    const contact = await msg.getContact();
    const chat = await msg.getChat();
    chat.sendMessage(`Hi @${contact.number}!`, {
      mentions: [contact],
    });
  }
});
module.exports = { app, socketIO };
`
i try running function getID() in client.on success, but client.getContact() not running

**Comment by PurpShell** [comment]
the way you get the id is very bad. 

Use client.getContactById(number) to the get the contact that way. 

Send me your error's stack trace.

Useful Links:
- [**Starter Guide**](https://waguide.pedroslopez.me)
- [**Documentation**](https://pedroslopez.me/whastapp-web.js)
- Questions? Chat with us on [**Discord**](https://discord.gg/wyKybbF)

Best regards, 

[PurpShell](https://github.com/PurpShell)

**Comment by PurpShell** [comment]
edge-case. 
Closing this issue, you are welcome to open it again if you think this was done in error. 

Useful Links:
- [**Starter Guide**](https://waguide.pedroslopez.me)
- [**Documentation**](https://pedroslopez.me/whastapp-web.js)
- Questions? Chat with us on [**Discord**](https://discord.gg/wyKybbF)

Best regards, 

[PurpShell](https://github.com/PurpShell)
