### ISSUE TITLE
Send List & Button Message

### ISSUE THREAD

**Issue by 0xT01** [pedroslopez/whatsapp-web.js#809]
Hello friends! I have seen people ordinarily send button & list message without official business registration, as shown below:
![WhatsApp Image 2021-08-04 at 15 50 43](https://user-images.githubusercontent.com/87315860/128152755-4010a528-1729-448d-b477-b4572efdcbbc.jpeg)
![WhatsApp Image 2021-08-04 at 15 50 43 (1)](https://user-images.githubusercontent.com/87315860/128152776-854cb897-da61-4367-a89f-96e5998c363a.jpeg)
I really hope it can be applied here in whatsapp-web.js.
Thanks for whatsapp-web.js team!

**Comment by PurpShell** [comment]
Hey! Have you taken a few seconds to look at the pull requests tab? I and @tuyuribr have worked on this, and all we can say is that it's coming soon. Take a look at #756

**Comment by 0xT01** [comment]
Ok. Thanks
