### ISSUE TITLE
We were also forced to downgrade to v2 due to this issue. Why you don't consider to build the library to a single file? This would increase the load performance, compatibility and decrease the size of the library.

### ISSUE THREAD

**Issue by Kristrue** [pedroslopez/whatsapp-web.js#903]
We were also forced to downgrade to v2 due to this issue. Why you don't consider to build the library to a single file? This would increase the load performance, compatibility and decrease the size of the library. 

_Originally posted by @tenbits in https://github.com/node-fetch/node-fetch/issues/1299#issuecomment-927186792_

**Comment by pedroslopez** [comment]
Seems unrelated / spam. Closing. Please explain if you think this was done in error.
